#ifndef TYPE_H_
#define TYPE_H_

#define DEFAULT_MESSAGE_LENGTH 1024

#define MAX_TOKEN_LENGTH 20
#define MAX_USERNAME_LENGTH 64
#define MAX_PASSWORD_LENGTH 64
#define MAX_QUESTION_LENGTH 64
#define MAX_ANSWER_LENGTH 64
#define MAX_FILENAME_LENGTH 128
#define MAX_PATH_LENGTH 128
#define MAX_HASH_LENGTH 128
#define MAX_NUMBER_LENGTH 20
#define MAX_SID_LENGTH 20
#define MAX_STATUS_LENGTH 8

#define TOKEN_LENGTH (MAX_TOKEN_LENGTH+1)
#define USERNAME_LENGTH (MAX_USERNAME_LENGTH+1)
#define PASSWORD_LENGTH (MAX_PASSWORD_LENGTH+1)
#define QUESTION_LENGTH (MAX_QUESTION_LENGTH+1)
#define ANSWER_LENGTH (MAX_ANSWER_LENGTH+1)
#define SID_LENGTH (MAX_SID_LENGTH+1)
#define FILENAME_LENGTH (MAX_FILENAME_LENGTH+1)
#define PATH_LENGTH (MAX_PATH_LENGTH+1)
#define HASH_LENGTH (MAX_HASH_LENGTH+1)
#define NUMBER_LENGTH (MAX_NUMBER_LENGTH+1)

#define STATUS_LENGTH (MAX_STATUS_LENGTH+1)

#endif